### PR TITLE
New zoom button

### PR DESCRIPTION
**Pull request by Suzie97**
This PR adds a new zoom button that is more consistent with the elementary apps. 

# Screenshot
Screenshot from 2021-09-04 22-11-59

# Prior Art
## elementary Code
Screenshot from 2021-09-04 22-03-14

## Akira
Sorry, no screenshots :(

# Features
- If we Ctrl + Click on the button, it pops up a text entry, and the user can enter the custom zoom value if they want finer control.
- Pressing up and down on the keyboard while the text entry is focused, changes the zoom level.
- If the zoom value entered is less than the minimum canvas zoom, or more than the maximum canvas zoom, the app will automatically zoom to the minimum and maximum values without passing the limit.

This offers the same level of functionality as the previous spin button but is more consistent with the system.

### CODE REVIEW

**Comment by phase1geo** [comment]
I've been playing around with the implementation.  I like the new layout of the zoom buttons.  Clicking on the zoom percentage button to return to 100% is okay.  But the Control-click implementation is weird and a bit buggy.  The zoom menu as a whole is a popup window.  Adding a popup from a popup is not good UI design in my opinion.

I would suggest that we do one of the following:

1. Convert the middle button text to an entry.  By default, it would be displayed as flat text (not editable and without editing borders, background, etc.)  If the user Control-clicks on the button, the entry would be placed into editable mode and the text border and background would resemble a typical entry button.  We would need to fix a bunch of issues when editing the value.

2. Remove Control-click from the middle button altogether.  Instead, add Control click for moving in smaller increments (5 or 10?) and Shift-Control click for increments of 1 when clicking the plus or minus buttons.

3. Remove Control-click from the middle button.  Leave the remaining functionality as is.

**Comment by Suzie97** [comment]
What do you think about moving the zoom button out of the popover and placing it directly on the headerbar??

Zooming is something the user will do 100s or even 1000s of times, and he/she might like to use the mouse for that. So in that case, I think having the zoom button in the headerbar itself will improve the experience a lot. Currently, the popover is used so that we have a place to show the zoom to fit window shortcut. If we decide to get rid of the popover, we'll need to think about a way to communicate that to the user, or even not show it at all, or maybe Ctrl + Shift + Click on the zoom button.

**Comment by phase1geo** [comment]
I don't have a problem with the zoom popover itself.  My issue is that when Control-click is used on the middle button within the popover, it causes a secondary popover to be displayed, allowing the user to hand-edit the zoom value.  I'm not suggesting that we remove the main zoom popover.

**Comment by Suzie97** [comment]
> I don't have a problem with the zoom popover itself. My issue is that when Control-click is used on the middle button within the popover, it causes a secondary popover to be displayed, allowing the user to hand-edit the zoom value.
> 
> I'm not suggesting that we remove the primary zoom popover. I think that is both expected and required.

I imagine a workflow where the user will be zooming multiple times. So opening a popover everytime he/she needs to zoom looks tedious. And currently the zoom popover only has the zoom button and the zoom to fit window button. So I was saying that if we move them to the headerbar, your Ctrl+Click to open a popover inside another popover issue will be solved. And since we have space on the headerbar, doings so might be a good idea.

Prior art in elementary OS includes the code app, where all the File actions (save, open, save as, etc) are in the headerbar. 

So this approach also looks more consistent with other apps.

What are your thoughts?

**Comment by phase1geo** [comment]
I don't think that people will be zooming a ton within Annotator. If they do, they will probably just learn/use keyboard shortcuts. Placing the zoom features concisely within the zoom popover would be in keeping with how most elementary apps handle zoom features.

**Comment by Suzie97** [comment]
Out of your proposed alternatives, I like the 2nd one the most. How should we communicate that to the user? Display that in a tooltip, or use buttons similar to the Zoom to Fit Page button below the main zoom button?

**Comment by phase1geo** [comment]
Tooltip

**Comment by phase1geo** [comment]
I have replaced the existing zoom functionality with an implementation of my own in the master branch.

**Pull request closed without merging**
